Backlog Checker/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Backlog_Checker.Controllers
{
    public class FeedbackController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Backlog Checker/Controllers/RouletteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Backlog_Checker.Controllers
{
    public class RouletteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Backlog Checker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backlog_Checker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/compiled.css" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script src="https://kit.fontawesome.com/64a534f152.js" crossorigin="anonymous"></script>
    <!--<link rel="stylesheet" href="~/css/site.css" />-->
</head>
<body class="@ViewData["PageTitle"]">
    <nav class="navbar">
        <div class="wrapper">
            <a class="brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/logo-dark-green-small-transparent.png" /></a>
            <div class="">
                <ul class="navbar-nav">
                    <li class="nav-item current">
                        <i class="fas fa-chart-line"></i><a class="nav-link current" asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <i class="fas fa-play"></i><a class="nav-link" asp-area="" asp-controller="Games" asp-action="Index">Games</a>
                    </li>
                    <li class="nav-item">
                        <i class="far fa-id-card"></i><a class="nav-link" asp-area="" asp-controller="Account" asp-action="Profile">Profile</a>
                    </li>
                    <!--
                    <li class="nav-item">
                        <i class="fas fa-compress-alt"></i><a class="nav-link" asp-area="" asp-controller="Games" asp-action="Compare">Compare</a>
                    </li>
                    <li class="nav-item">
                        <i class="fas fa-dice-six"></i><a class="nav-link" asp-area="" asp-controller="Roulette" asp-action="Index">Backlog Roulette</a>
                    </li>

                    <li class="nav-item">
                        <i class="fas fa-comment-dots"></i><a class="nav-link" asp-area="" asp-controller="Feedback" asp-action="Index">Feedback</a>
                    </li>
                    -->
                </ul>
            </div>
        </div>
    </nav>

    <!--layout-container-->
    <section class="layout-container">
        <!--header-->
        <header>
            <div class="profile">

                @{
                    //Get username from session
                    var sessionName = new Byte[20];
                    bool nameOK = Context.Session.TryGetValue("username", out sessionName);

                    if (nameOK)
                    {
                        string result = System.Text.Encoding.UTF8.GetString(sessionName);
                        <a asp-area="" asp-controller="Account" asp-action="Profile">@result</a>
                        <a class="danger logout" asp-area="" asp-controller="Account" asp-action="LogOut">Log Out</a>
                    }
                    else
                    {

                        <a asp-area="" asp-controller="Account" asp-action="Login">Log in</a>
                        <a asp-area="" asp-controller="Account" asp-action="Register">Register</a>

                    }
                }

            </div>
        </header>
        <!--/header-->
        <!--Main-->
        <main role="main">
            <div class="wrapper">
                @RenderBody()
            </div>
        </main>
        <!--/Main-->
    </section>
    <!--/layout-container-->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>